### ISSUE TITLE
Fatal Error when module is enabled.  

### ISSUE THREAD

**Issue by biggeeves** [biggeeves/dark_mode#1]
REDCap crashed due to an unexpected PHP fatal error!Error message: Uncaught ArgumentCountError: Too few arguments to function DCC\DarkModeExternalModule\DarkModeExternalModule::redcap_every_page_top(), 1 passed and exactly 3 expected in /var/www/html/redcap/modules/dark_mode_v0.7/DarkModeExternalModule.php:42 Stack trace: #0 [internal function]: DCC\DarkModeExternalModule\DarkModeExternalModule->redcap_every_page_top(NULL) #1 /var/www/html/redcap/redcap_v9.6.3/ExternalModules/classes/ExternalModules.php(2436): call_user_func_array(Array, Array) #2 /var/www/html/redcap/redcap_v9.6.3/ExternalModules/classes/ExternalModules.php(2536): ExternalModules\ExternalModules::startHook('dark_mode', 'v0.7', Array) #3 /var/www/html/redcap/redcap_v9.6.3/ExternalModules/classes/ExternalModules.php(2551): ExternalModules\ExternalModules::ExternalModules\{closure}('dark_mode', 'v0.7') #4 /var/www/html/redcap/redcap_v9.6.3/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook('every_page_top', Array) #5 /var/www/html/redcap/redcap_v9.6.3/Classes/HtmlPage.php(193): Hooks::call('redcap_every_pa...', Array) #6 /var/www/html/redcap/redcap_v9.6.3/Home/index.php(43): HtmlPage->PrintHeader() #7 /var/www/html/redcap/redcap_v9.6.3/home.php(10): require_once('/var/www/html/r...') #8 /var/www/html/redcap/index.php(11): include('/var/www/html/r...') #9 {main} thrownFile: /var/www/html/redcap/modules/dark_mode_v0.7/DarkModeExternalModule.phpLine: 42

**Comment by biggeeves** [comment]
Fixed in version 0.8
